// Source representation of the Wasm module generated by gen_rust_fibonacci.
// This file is NOT compiled directly -- the .wasm is generated via the Go
// bytecode emitter. It exists purely as documentation to prove that the
// runner is language-agnostic: this Rust function compiles to the exact
// same Wasm bytecode that the Go generator produces.
//
// Compile (if you have rustc installed):
//   rustc --target wasm32-unknown-unknown --crate-type cdylib -O fibonacci.rs -o rust_fibonacci.wasm

#[no_mangle]
pub extern "C" fn fibonacci(n: u32) -> u32 {
    if n <= 1 {
        return n;
    }
    let (mut a, mut b) = (0u32, 1u32);
    for _ in 2..=n {
        let tmp = a + b;
        a = b;
        b = tmp;
    }
    b
}
